name: CI Pipeline

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.11
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run pytest
      run: pytest fast_api/
      
    - name: Run mypy
      run: mypy fast_api/
    
    - name: Run black
      run: black --diff --check fast_api/
    
    - name: Run isort
      run: isort --check-only --diff fast_api/
    
    - name: Run flake8
      run: flake8 fast_api/
